package model

import (
	"time"
)

// DefaultSeedProjects returns initial projects with realistic data (including full Dymmer backlog).
func DefaultSeedProjects() []*Project {
	now := time.Now()
	dymmer := &Project{
		Slug:        "dymmer",
		Name:        "Dymmer",
		Description: "Cloud platform for managing domains, cloud projects, DNS zones, and mail services.",
		CreatedAt:   now,
		UpdatedAt:   now,
		Tasks: []Task{
			// Monetization
			{
				ID:          "1",
				Title:       "PayPal Subscriptions",
				Description: "Recurring billing for domains and projects — TLD plan definitions, pending review queue, Oban background jobs.",
				Group:       "Monetization",
				Size:        SizeXL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "spec 08-24",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "2",
				Title:       "Plan upgrade / downgrade from /plan",
				Description: "Currently informational only. Missing real purchase/switch flow for PlanType.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "TODO",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "3",
				Title:       "Manual project renewal",
				Description: "Verified in codebase: no renewal route in UI — wizard says 'we\\'ll be in touch about renewing next month'.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "finding 08-29",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "4",
				Title:       "Replace custom scheduler with Oban",
				Description: "Current warn_days_before mutates array before confirming email delivery.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "TODO 08-29",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "5",
				Title:       "Lock domain on repeated payment failure",
				Description: "When PayPal suspends subscription — via own nameservers or registrar API.",
				Group:       "Monetization",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "TODO 08-29",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "6",
				Title:       "Direct PayPal payment on zero balance",
				Description: "Authorize + capture/void, never charges if provisioning fails.",
				Group:       "Monetization",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        true,
				Tag:         "08-28",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "7",
				Title:       "Flow 4 — Addon on existing project",
				Description: "Host capacity card with daily prorating.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        true,
				Tag:         "08-28",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "8",
				Title:       "Flow 3 — Project purchase",
				Description: "4-step wizard, base plan + extra hosts.",
				Group:       "Monetization",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        true,
				Tag:         "08-27/28",
				CreatedAt:   now,
				UpdatedAt:   now,
			},

			// Infrastructure
			{
				ID:          "9",
				Title:       "Host Roles & Server Types",
				Description: "web_server/web_static on Host, host_ips table, merge MailServers into Host.",
				Group:       "Infrastructure",
				Size:        SizeL,
				Tier:        Tier5,
				Done:        false,
				Tag:         "spec 08-17",
				CreatedAt:   now,
				UpdatedAt:   now,
			},

			// Redesign
			{
				ID:          "10",
				Title:       "Public landing page",
				Description: "Sprint 9, paused — waiting for real pricing in database.",
				Group:       "Redesign",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "Sprint 9",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "11",
				Title:       "News page (/news)",
				Description: "/news — missing mockup and redesign.",
				Group:       "Redesign",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "TODO",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "12",
				Title:       "Error pages (400/404/500)",
				Description: "Product decision pending on brand alignment.",
				Group:       "Redesign",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "TODO",
				CreatedAt:   now,
				UpdatedAt:   now,
			},

			// Domains
			{
				ID:          "13",
				Title:       "Editable WHOIS contacts",
				Description: "Currently read-only — requires edit form + update_contacts/2 in provider.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "TODO",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "14",
				Title:       "SSL certificate management tab",
				Description: "Missing field in Domain; requires certificate verification pipeline.",
				Group:       "Domains",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "Sprint 8",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "15",
				Title:       "Purchase additional email forwardings",
				Description: "Unlike mailboxes, forwardings only have the fixed plan limit.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "finding 08-31",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "16",
				Title:       "Purchasing mailboxes/forwardings on DNS zones crashes",
				Description: "MailboxesAddon prorates against domain.expires_at, which DNS zones lack (nil).",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "finding 08-31",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "17",
				Title:       "LiveView migration for Mailboxes and Forwardings",
				Description: "Replaced legacy controllers with LiveView at /mail/:domain_id.",
				Group:       "Domains",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        true,
				Tag:         "08-31",
				CreatedAt:   now,
				UpdatedAt:   now,
			},

			// Bugs
			{
				ID:          "18",
				Title:       "Deleting account with billing history crashes",
				Description: "Accounts.delete/1 fails with Ecto.ConstraintError if user has subscriptions.",
				Group:       "Bugs",
				Size:        SizeS,
				Tier:        Tier1,
				Done:        false,
				Tag:         "finding 08-30",
				CreatedAt:   now,
				UpdatedAt:   now,
			},

			// Hosts
			{
				ID:          "19",
				Title:       "Hide Access credentials when editing shared host",
				Description: "Security check — credentials field must be hidden if host is not owned by user.",
				Group:       "Hosts",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "TODO",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "20",
				Title:       "Cloud provider OAuth integrations (6)",
				Description: "OVH, Hetzner, AWS, Azure, Google Cloud, and Coolify import support in Add Host.",
				Group:       "Hosts",
				Size:        SizeXL,
				Tier:        Tier5,
				Done:        false,
				Tag:         "TODO",
				CreatedAt:   now,
				UpdatedAt:   now,
			},
		},
	}

	conta := &Project{
		Slug:        "conta",
		Name:        "Conta",
		Description: "Automated billing and fiscal invoicing service for Dymmer and external clients.",
		CreatedAt:   now,
		UpdatedAt:   now,
		Tasks: []Task{
			{
				ID:          "1",
				Title:       "Batch PDF invoice generation",
				Description: "Monthly billing PDF rendering using Typst or headless Chromium.",
				Group:       "Billing",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "2",
				Title:       "Invoice issued webhook notification",
				Description: "Notify Dymmer when a fiscal invoice has been signed and delivered.",
				Group:       "Integrations",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				CreatedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "3",
				Title:       "VIES VAT number validation",
				Description: "Automated query to EU VIES service for cross-border VAT exemption.",
				Group:       "Tax",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        true,
				CreatedAt:   now,
				UpdatedAt:   now,
			},
		},
	}

	return []*Project{dymmer, conta}
}
