package model

import (
	"time"
)

// DefaultSeedProjects returns initial projects with realistic data (including full Dymmer backlog).
func DefaultSeedProjects() []*Project {
	now := time.Now()
	dymmer := &Project{
		Slug:        "dymmer",
		Name:        "Dymmer",
		Description: "Cloud platform for managing domains, cloud projects, DNS zones, and mail services.",
		InsertedAt:   now,
		UpdatedAt:   now,
		Tasks: []Task{
			{
				ID:          "1",
				Title:       "Suscripciones PayPal",
				Description: "Cobro recurrente para dominios y proyectos — Plan por TLD, cola de revise pendiente, jobs de Oban. Diseño completo y verificado en sandbox; cero código. La renovación manual ya funciona hoy, esto automatiza.",
				Group:       "Monetization",
				Size:        SizeXL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "2",
				Title:       "Cambio de plan desde /plan",
				Description: "Hoy solo informativo. Falta el flujo real de compra/cambio de PlanType.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "3",
				Title:       "Renovación manual de proyectos",
				Description: "Verificado en código: no existe ninguna vía en la app — el wizard de creación literalmente dice \"we'll be in touch about renewing next month\". Domains sí tiene renovación; Projects no tiene nada hoy.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "4",
				Title:       "Sustituir el scheduler por Oban",
				Description: "El warn_days_before actual muta el array antes de confirmar el envío del email — un fallo de envío pierde el aviso para siempre. Afecta la fiabilidad de los avisos de expiración reales.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "5",
				Title:       "Bloquear dominio por impago repetido",
				Description: "Cuando PayPal suspenda la suscripción — vía nameservers propios o API del registrador. Solo el principio, sin diseño de detalle.",
				Group:       "Monetization",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "6",
				Title:       "Pago directo con PayPal a saldo cero",
				Description: "Authorize + capture/void, nunca cobra si la compra falla.",
				Group:       "Monetization",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "7",
				Title:       "Flujo 4 — addon sobre proyecto existente",
				Description: "Tarjeta \"Host capacity\", prorrateo por días.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "8",
				Title:       "Flujo 3 — compra de proyecto",
				Description: "Wizard de 4 pasos, base + hosts extra.",
				Group:       "Monetization",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "9",
				Title:       "Addon de buzones soporta carrito",
				Description: "mailboxes_quantity/tier en Cart.",
				Group:       "Monetization",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "10",
				Title:       "Addons de dominio se arrastran a la renovación",
				Description: "Con cobro real de segunda transacción.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "11",
				Title:       "Identidad de empresa como contacto de dominio",
				Description: "type/company_name en el WHOIS de un dominio.",
				Group:       "Monetization",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "12",
				Title:       "Roles de Host",
				Description: "web_server/web_static en Host, tabla host_ips, fusión de MailServers en Host. 0% implementado — refactor de arquitectura, nada roto hoy sin él.",
				Group:       "Infrastructure",
				Size:        SizeL,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "13",
				Title:       "Cuenta y Facturación (Sprint 11)",
				Description: "Las 6 páginas reconstruidas como LiveViews (ProfileLive.*), salvo keys que se queda como controller re-vestido. /plan ya muestra PlanType + acceso a API; guardarraíl de borrado ampliado a proyectos y suscripciones activas (sustituye al de \"plan no-básico\", que desaparece con el modelo de entitlements).",
				Group:       "Redesign",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "14",
				Title:       "Landing pública",
				Description: "Sprint 9, pausado — bloqueado hasta que el precio real exista en BD. No afecta a clientes ya operando, sí a la captación de nuevos.",
				Group:       "Redesign",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "15",
				Title:       "Página de Noticias",
				Description: "/news — sin mockup, sin rediseñar.",
				Group:       "Redesign",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "16",
				Title:       "Páginas de error",
				Description: "400/404/500 — decisión de producto pendiente sobre si vale la pena un pase de marca.",
				Group:       "Redesign",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "17",
				Title:       "Limpieza: UserSessionController.new/2",
				Description: "Sin ninguna ruta que lo use — candidato a borrar.",
				Group:       "Redesign",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "18",
				Title:       "Gestión de zona DNS sin rediseñar: Records, Record Grants",
				Description: "Funcionan hoy, solo con patrón visual antiguo. Zonas, Mailboxes y Forwardings ya salieron de esta lista — tienen página rediseñada propia (ver abajo).",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "19",
				Title:       "SSL — tab descartado",
				Description: "Sin campo real en Domain; requeriría campo + verificación de certificados. Alcance por confirmar: ¿es responsabilidad de Dymmer o del host/reverse-proxy del propio usuario?",
				Group:       "Domains",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "20",
				Title:       "Contactos WHOIS editables",
				Description: "Hoy solo lectura — si el titular necesita corregir su info de contacto, no puede. Falta formulario + update_contacts/2 en el provider. UI propuesta: acordeón por rol (Owner/Admin/Billing/Technical); pendiente decidir si cada contacto admite datos independientes o se mantienen \"sincronizados\" en un único formulario.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "21",
				Title:       "Auto-Renewal — toggle descartado",
				Description: "Sin campo auto_renew ni scheduler — se resuelve como parte de PayPal Subscriptions. La renovación manual ya cubre el caso hoy.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "22",
				Title:       "Atajo de Transfer perdido al migrar",
				Description: "Proveedor+auth_id precargados — hoy hay que rellenarlos a mano.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "23",
				Title:       "Breadcrumb estilo /projects",
				Description: "Pendiente en las páginas de zona DNS.",
				Group:       "Domains",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "24",
				Title:       "DomainLive.Renew — cobertura de test",
				Description: "2 escenarios redundantes sin portar, no bloqueante.",
				Group:       "Domains",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "25",
				Title:       "DomainLive.Transfer — cobertura de test",
				Description: "1 escenario redundante sin portar.",
				Group:       "Domains",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "26",
				Title:       "Domain.email_type debería calcularse solo",
				Description: "Hoy es un campo persistido sin ningún editor en la UI desde que se borró Mail Settings — según el usuario, el valor correcto es implícito: :real con buzones, :virtual solo con redirecciones, :manual si el MX no apunta a un mail_server de Dymmer aunque tenga ambos. No bloquea nada hoy, pero se desincroniza solo.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "27",
				Title:       "No existe forma de comprar más redirecciones",
				Description: "A diferencia de los buzones (addon completo con precio y pantalla propia), las redirecciones solo tienen el límite fijo del plan — sin función de compra, precio, ni UI. El schema ya reserva :forwardings como tipo de SubscriptionDetail, nunca conectado.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "28",
				Title:       "Comprar buzones/redirecciones para una zona rompería hoy",
				Description: "DomainLive.MailboxesAddon prorratea contra domain.expires_at, que una zona nunca tiene (siempre nil) — reventaría en cuanto alguien lo intente. El botón \"Email\" ya existe en la zona; la compra en sí queda pendiente, decisión explícita del usuario.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "29",
				Title:       "Política al caducar la suscripción de buzones/redirecciones — decidida, sin implementar",
				Description: "Si el nuevo límite es menor que lo ya creado: nunca se borra nada, se deshabilitan al azar los que sobren y se notifica al usuario; lo deshabilitado no cuenta en el cómputo ni se puede reactivar sin hueco libre. Hoy no existe ningún mecanismo que detecte este caso.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "30",
				Title:       "Gestión de buzones y redirecciones — /mail/:domain_id",
				Description: "Sustituye por completo a los antiguos MailboxesController/ForwardingsController/\"Mail Settings\" (borrados, sin ningún camino de navegación real hacia ellos) — pestañas con listado, modal de alta/edición, cuotas (buzones comprados, redirecciones del plan — cero para zonas) y borrado.",
				Group:       "Domains",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "31",
				Title:       "Pago directo por PayPal para el addon de buzones",
				Description: "Mismo patrón zero-balance que la compra de dominios — authorize/capture vía custom_id de la orden, sin necesitar fila de Cart porque no se crea ningún dominio nuevo.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "32",
				Title:       "Zonas rediseñadas como LiveView",
				Description: "ZoneLive.New/ZoneLive.Show sustituyen a ZonesController#new/edit/create — misma pestaña de DNS Records que DomainLive.Show, abierta por defecto; cabecera con Email/Transfer a Dymmer/Delete.",
				Group:       "Domains",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "33",
				Title:       "Rediseño de la columna de acciones en /domains",
				Description: "Check ahora es un evento en vivo (solo admin, ya no recarga la página), Renew/Transfer/Delete en espacios fijos de un solo icono, más el nuevo acceso a Email por fila.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "34",
				Title:       "Contacts (WHOIS): tarjeta legible",
				Description: "Sustituye el inspect() crudo del struct de credenciales por una tarjeta con nombre/dirección/teléfono/email.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "35",
				Title:       "Toggles Transfer Lock/WHOIS Privacy sin estado de carga",
				Description: "Tardaban en responder sin ningún indicio visual, invitando a pulsar dos veces — ahora muestran un spinner mientras esperan al proveedor.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "36",
				Title:       "DNS Records: fila de \"vacío\" al filtrar sin resultados",
				Description: "hidden only:table-row, sin assign nuevo — cubre tanto \"sin registros de este tipo\" como \"sin ningún registro\".",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "37",
				Title:       "Modal Add/Edit Record no cerraba con Cancel/X",
				Description: "Un hook stopPropagation bloqueaba la delegación de eventos de LiveView para todo lo de dentro del modal, no solo el backdrop — sustituido por phx-click-away nativo.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "38",
				Title:       "Contador \"DNS Records\" excluía los NS",
				Description: "No coincidía con el listado sin filtrar que sí los muestra.",
				Group:       "Domains",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "39",
				Title:       "Wizard de creación — 3 arreglos de navegación",
				Description: "Aviso obsoleto sobre el addon de buzones en el carrito, doble \"volver\" confuso en el paso Select, botón \"Search\" desalineado + stepper rehecho en Tailwind propio.",
				Group:       "Domains",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "40",
				Title:       "Resellbiz — privacidad WHOIS activada",
				Description: "Incondicional en toda compra nueva, coste absorbido por Dymmer.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "41",
				Title:       "/domains rediseñado",
				Description: "DomainLive.Index con filtrado en vivo.",
				Group:       "Domains",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "42",
				Title:       "AdminLive.Dashboard — secciones ficticias",
				Description: "System Health, Backup/Clear Cache, audit log — ninguna tiene backend real. Te afecta a ti operando la plataforma, no al cliente final.",
				Group:       "Admin",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "43",
				Title:       "AdminLive.Users — rol / último login / crear usuario",
				Description: "Sin campo/flujo real detrás de ninguno de los tres. Visibilidad operativa, no bloquea al cliente final.",
				Group:       "Admin",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "44",
				Title:       "Modo de correo manual vs. gestionado",
				Description: "Planes de correo por dominio, servidor asignado automáticamente, validación anti-abuso del MX.",
				Group:       "Mail",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "45",
				Title:       "Procesar informes DMARC agregados",
				Description: "IMAP + parseo de XML + estadística por dominio. Buzón ya habilitado.",
				Group:       "Mail",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "46",
				Title:       "Validar destination de forwarding como email",
				Description: "Hoy acepta texto arbitrario.",
				Group:       "Mail",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "47",
				Title:       "Métricas — tipo summary",
				Description: "Percentiles p50/p90/p99 vía ingesta push — sin mecanismo ni spec propio.",
				Group:       "Sprint 7",
				Size:        SizeL,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "48",
				Title:       "Actions — historial de ejecución",
				Description: "Sin campos last_run_at/status, ni tabla de historial.",
				Group:       "Sprint 7",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "49",
				Title:       "Actions — acciones rápidas fijas",
				Description: "Deploy All/Restart/Backup/Clear Cache — sin schema que las represente.",
				Group:       "Sprint 7",
				Size:        SizeM,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "50",
				Title:       "Actions — log de ejecución persistente",
				Description: "Depende de tener historial de ejecución primero.",
				Group:       "Sprint 7",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "51",
				Title:       "Domains — coste/año",
				Description: "Sin campo de precio en Domain ni pricing por proveedor mostrado.",
				Group:       "Sprint 7",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "52",
				Title:       "Métricas — test de unicidad al editar",
				Description: "Solo cubierto el camino de creación, no el de edición.",
				Group:       "Sprint 7",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "53",
				Title:       "Métricas — N+1 en reload_lines/1",
				Description: "Recarga todas las líneas del entorno ante cualquier mutación. Aceptable a la escala actual.",
				Group:       "Sprint 7",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "54",
				Title:       "Métricas — eje Y sin formatear",
				Description: "La gráfica expandida no escala por unidad. Cosmético.",
				Group:       "Sprint 7",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "55",
				Title:       "Migrar <.simple_form> a <.form>+<.input>",
				Description: "~45 usos en 24 ficheros. Bloquea mix precommit limpio (warnings de deprecación esperados mientras tanto). Invisible para el usuario final.",
				Group:       "Migraciones pendientes",
				Size:        SizeL,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "56",
				Title:       "input_class/0 duplicado en 3 sitios",
				Description: "Candidato a helper compartido en html_helpers.",
				Group:       "Migraciones pendientes",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "57",
				Title:       "Borrar cuenta con historial de facturación crashea",
				Description: "Accounts.delete/1 revienta con Ecto.ConstraintError sin capturar si el usuario tiene alguna suscripción (incluso deshabilitada) — falta on_delete en las FKs de facturación. Requiere decisión de retención de datos, no solo código.",
				Group:       "Bugs conocidos",
				Size:        SizeS,
				Tier:        Tier1,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "58",
				Title:       "Flash de error sin navegación en HostLive.FormComponent",
				Description: "Arreglado sin navegación: el error se añade al campo :hostname del changeset y se muestra en su <.error> ya existente, modal abierto.",
				Group:       "Bugs conocidos",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "59",
				Title:       "Apps: no se puede guardar solo con el nombre",
				Description: "enabled_ops exigía no-vacío siempre. Arreglado: solo se exige cuando command_type está establecido, igual que el resto de validaciones condicionales del módulo.",
				Group:       "Bugs conocidos",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "60",
				Title:       "Deployments \"custom\" con decode: true",
				Description: "Arreglado con el mismo fix que ya tenía Actions: decode: false + leer info[\"message\"]. Verificado con Hemdal.Host.Local real, sin mocks.",
				Group:       "Bugs conocidos",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "61",
				Title:       "[Seguridad] IDOR en remove_line/reorder_lines",
				Description: "7 páginas de project lines sin comprobación de propiedad — arreglado con line_belongs_to_project?/2.",
				Group:       "Bugs conocidos",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "62",
				Title:       "El scheduler de avisos de renovación crasheaba siempre",
				Description: "Construía el enlace de renovación con un helper de ruta de controlador (Router.Helpers.domains_url(..., :renew, ...)) que ya no existe desde que esa página pasó a LiveView — cualquier suscripción con un aviso pendiente tumbaba el scheduler entero antes de enviar nada. Los emails de expiración llevaban rotos desde esa migración, en silencio.",
				Group:       "Bugs conocidos",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "63",
				Title:       "Toggle visible de tema",
				Description: "Hoy data-theme se fija una vez al cargar — sin control manual en la UI.",
				Group:       "Theme",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "64",
				Title:       "Recargar CodeMirror al cambiar de tema",
				Description: "Depende del toggle de arriba — el editor de env vars no se reconfigura en caliente.",
				Group:       "Theme",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "65",
				Title:       "Selector de color de Actions — swatch vs. render",
				Description: "El color que se ve al elegir no es exactamente el que se pinta ya guardado en modo oscuro.",
				Group:       "Theme",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "66",
				Title:       "Auditoría de cobertura dark: — HostLive.Show + DomainLive.Edit",
				Description: "0 clases dark: pese a llevar el diseño nuevo — pareja añadida a las dos.",
				Group:       "Theme",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "67",
				Title:       "Dashboard — breadcrumb/cabecera sin modo oscuro",
				Description: "Mismo síntoma que HostLive.Show — pareja de clases dark: añadida. De paso, botón \"+ New Domain\" junto a \"+ New Project\".",
				Group:       "Theme",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "68",
				Title:       "Recent activity real, no aproximado",
				Description: "Usa updated_at de proyectos hoy — necesita un audit-log de acciones de usuario por proyecto.",
				Group:       "Dashboard",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "69",
				Title:       "Asociar dominio/records a una app",
				Description: "Requiere pin ProjectLineDeployment ↔ ProjectLineDomainRecord. Hoy es posible a mano creando el record y apuntándolo a la IP del host.",
				Group:       "Deployments / Apps detail",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "70",
				Title:       "Botón Re-deploy + versión desplegada",
				Description: "Verificado en código: ProjectLineDeployment solo supervisa procesos ya corriendo (systemctl/docker/pm2/...) — Dymmer no hace CI/CD desde repositorio. Esto es un producto distinto, no una función rota.",
				Group:       "Deployments / Apps detail",
				Size:        SizeL,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "71",
				Title:       "Historial de Deploys",
				Description: "Lista con hash/mensaje/estado — depende de que exista Re-deploy real, que está fuera del alcance actual del producto.",
				Group:       "Deployments / Apps detail",
				Size:        SizeM,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "72",
				Title:       "Uptime % histórico",
				Description: "Solo se guarda el último check, no una serie temporal.",
				Group:       "Deployments / Apps detail",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "73",
				Title:       "Requests/min y Response time (p95)",
				Description: "Sin colector de tráfico HTTP específico en el catálogo de métricas.",
				Group:       "Deployments / Apps detail",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "74",
				Title:       "Stats de Apps — \"Last Deploy\" sin dato real",
				Description: "status_at es la última comprobación, no un deploy real — etiqueta engañosa, corregible sin construir Re-deploy.",
				Group:       "Deployments / Apps detail",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "75",
				Title:       "Refactor de line_form_component.ex",
				Description: "Demasiado código incrustado en render.",
				Group:       "Deployments / Apps detail",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "76",
				Title:       "Renombrar deployment → app",
				Description: "Para que el código haga match con el nombre ya usado en la interfaz.",
				Group:       "Deployments / Apps detail",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "77",
				Title:       "Campo \"Repositorio\" en Deployment",
				Description: "Necesario para Re-deploy o historial basado en git — mismo alcance fuera de producto que ambos.",
				Group:       "Deployments / Apps detail",
				Size:        SizeS,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "78",
				Title:       "Logs recientes embebidos en App Detail",
				Description: "El streaming ya existe (LogFollow) — solo falta conectarlo aquí filtrado a la línea.",
				Group:       "Deployments / Apps detail",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "79",
				Title:       "3 iconos rotos en assets/apps/",
				Description: "Nuxt, Sinatra, Java — re-descargados de Simple Icons.",
				Group:       "Deployments / Apps detail",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "80",
				Title:       "Configurar entornos del proyecto",
				Description: "Nombre/slug/color por entorno — hoy dev/staging/prod están fijos en código.",
				Group:       "Projects",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "81",
				Title:       "Bug: formularios pierden edición en Logs/Metrics",
				Description: "IDs de campo duplicados: to_form(changeset) generaba el mismo id para todas las líneas del mismo tipo. Arreglado escopando el id por línea en LineFormComponent.assign_form/2.",
				Group:       "Projects",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "82",
				Title:       "URL /blocks para la vista por bloques",
				Description: "Afecta también al breadcrumb.",
				Group:       "Projects",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "83",
				Title:       "Contador de variables de entorno",
				Description: "Sumaba filas de la tabla obsoleta Secret — ahora suma entradas reales de EnvFile.",
				Group:       "Projects",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "84",
				Title:       "Selector Global/App en el editor de env vars",
				Description: "Desplegable para elegir sobre qué se está trabajando.",
				Group:       "Projects",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "85",
				Title:       "Error al guardar sin variables de entorno",
				Description: "raw_content ya no exige contenido no-vacío.",
				Group:       "Projects",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "86",
				Title:       "Rutas de entorno en la URL, no en query param",
				Description: "/projects/:id/:env(/...), con redirect por defecto a /dev.",
				Group:       "Projects",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "87",
				Title:       "Ocultar \"Access\" al editar un host ajeno",
				Description: "Último campo antes de los botones — no debe verse si el host no es tuyo. Fuga de información entre usuarios.",
				Group:       "Hosts",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "88",
				Title:       "OAuth — sección propia en Hosts",
				Description: "Listar proveedores con API activa para importar datos de hosts.",
				Group:       "Hosts",
				Size:        SizeM,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "89",
				Title:       "Integraciones OAuth de proveedores (6)",
				Description: "OVH, Hetzner, AWS, Azure, Google Cloud y Coolify — cada uno como opción de importación en \"Add Host\". Añadir hosts a mano ya funciona hoy.",
				Group:       "Hosts",
				Size:        SizeXL,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "90",
				Title:       "3 pantallas de Hosts seguían con el diseño antiguo — hecho",
				Description: "Terminal, Grants, Accesses — verificado en código: ya usan Hero Icons y breadcrumb.",
				Group:       "Hosts",
				Size:        SizeL,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "91",
				Title:       "Terminal no funcionaba",
				Description: "Hosts.shell/2 sin guard de :exit — crasheaba el LiveView entero.",
				Group:       "Hosts",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "92",
				Title:       "Quitar selector SSH/OAuth en el formulario de host",
				Description: "Solo existe SSH manual hoy.",
				Group:       "Hosts",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "93",
				Title:       "Tarjetas para apps (alcance propio)",
				Description: "Igual que en Projects pero acotado a una sola app.",
				Group:       "Apps",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "94",
				Title:       "Tarjeta de métricas por app",
				Description: "Uno o varios hosts + la app, vía telemetry o PID.",
				Group:       "Apps",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "95",
				Title:       "Tarjeta de logs por app",
				Description: "Uno o varios hosts + dónde encontrar los logs de esa app.",
				Group:       "Apps",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "96",
				Title:       "Revisión periódica de MX + flag enabled",
				Description: "Si un CNAME cambia, deshabilitar el record y notificar. Depende de Notificaciones.",
				Group:       "Records",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "97",
				Title:       "MX solo a servidores propios con permiso",
				Description: "Resolver el nombre y validar si apunta a infraestructura de Dymmer sin contrato — prevención de abuso.",
				Group:       "Records",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "98",
				Title:       "Seleccionar IP de host para A/AAAA",
				Description: "En vez de escribir la IP a mano.",
				Group:       "Records",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "99",
				Title:       "Validar ciclos de CNAME",
				Description: "Un CNAME que resuelve sobre sí mismo debe dar error de \"loop\".",
				Group:       "Records",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "100",
				Title:       "Sistema de notificaciones (schema + PubSub)",
				Description: "Tabla nueva enlazada al usuario, tipo/contenido/uri/estado, propagación a LiveViews abiertas. Hoy el aviso crítico ya llega por email.",
				Group:       "Notifications",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "101",
				Title:       "Notificación: expiración de dominio",
				Description: "Depende del sistema de arriba.",
				Group:       "Notifications",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "102",
				Title:       "Notificación: cambio de estado de dominio",
				Description: "Depende del sistema de arriba.",
				Group:       "Notifications",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "103",
				Title:       "Notificación: record deshabilitado automáticamente",
				Description: "Ligado a la revisión periódica de MX en Records.",
				Group:       "Notifications",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "104",
				Title:       "Estudiar el protocolo MCP para Dymmer",
				Description: "Exponer servidor propio y/o consumir servidores MCP externos — fase de investigación.",
				Group:       "MCP",
				Size:        SizeS,
				Tier:        Tier5,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "105",
				Title:       "current_scope.user en vez de current_user",
				Description: "Barrido pendiente por todo el código — aparece duplicado dos veces en el propio TODO.md.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "106",
				Title:       "Migrar Dymmer.Api.Abstract de Tesla a Req",
				Description: "Único uso de Tesla que queda — ojo con Memoize y los mocks globales.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "107",
				Title:       "Empaquetar paypal para Hex de verdad",
				Description: "Hoy fijado a GitHub solo por el módulo de soporte de tests.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "108",
				Title:       "Gettext en todos los textos",
				Description: "Aplicar de forma consistente en toda la app.",
				Group:       "General",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "109",
				Title:       "Separar bundles de JS por librería",
				Description: "xterm/apex/easymde en ficheros propios para reducir el tamaño de app.js.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "110",
				Title:       "Descargar fuentes en vez de CDN",
				Description: "Evita tener que relajar la CSP.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "111",
				Title:       "Test: la API key no debe borrarse con logout",
				Description: "Sin cobertura hoy.",
				Group:       "General",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "112",
				Title:       "Revisar sentido de las opciones del sidebar",
				Description: "Pase de coherencia general.",
				Group:       "General",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "113",
				Title:       "Migración de carrito — índice único parcial",
				Description: "DROP del índice viejo + índice parcial solo sobre status = 'waiting'.",
				Group:       "General",
				Size:        SizeXS,
				Tier:        Tier4,
				Done:        false,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "114",
				Title:       "Bypass de admin roto en auth por API token",
				Description: "fetch_api_user/2 no precargaba :plan — el bypass nunca coincidía. Centralizado y arreglado.",
				Group:       "General",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "115",
				Title:       "earmark — XSS sin parche (CVE)",
				Description: "Migrado a MDEx en los dos sitios reales.",
				Group:       "General",
				Size:        SizeM,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "116",
				Title:       "decimal — DoS por exponente (CVE)",
				Description: "Resuelto vía 3 dependencias git con rango estricto.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "117",
				Title:       "with en vez de ifs anidados",
				Description: "Convención escrita en AGENTS.md.",
				Group:       "General",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "118",
				Title:       "Usar :for/:if en HEEx",
				Description: "Convención escrita en AGENTS.md.",
				Group:       "General",
				Size:        SizeXS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "119",
				Title:       "Unificar app.html.heex y live.html.heex",
				Description: "Resuelto como parte del Sprint 2.",
				Group:       "General",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        true,
				Tag:         "",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
		},
	}

	conta := &Project{
		Slug:        "conta",
		Name:        "Conta",
		Description: "Double-entry bookkeeping, invoicing, and bank reconciliation engine built with Elixir, Commanded, and EventStore.",
		InsertedAt:   now,
		UpdatedAt:   now,
		Tasks: []Task{
			{
				ID:          "1",
				Title:       "Propagate :consistency in Conta.Projector",
				Description: "Conta.Projector drops :consistency before passing options to Commanded.Event.Handler, causing dispatch(..., consistency: :strong) to be a silent no-op across all projectors.",
				Group:       "Core",
				Size:        SizeM,
				Tier:        Tier1,
				Done:        false,
				Tag:         "EventStore",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "2",
				Title:       "Fix condition :id generation in Reconciliation.get_set_match_rule/1",
				Description: "SetMatchRule conditions built from read model without explicit :id trigger Ecto duplicate primary key warnings when adding 2+ conditions in edit form.",
				Group:       "Reconciliation",
				Size:        SizeS,
				Tier:        Tier2,
				Done:        false,
				Tag:         "Ecto",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "3",
				Title:       "Automator Lua script result validation",
				Description: "Add shared validation pass for Importer, Shortcut, and Filter automators to prevent silent command drops and FunctionClauseErrors on malformed return values.",
				Group:       "Automators",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "Lua",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "4",
				Title:       "Bot support for complex & multi-currency transactions",
				Description: "Add conversational flow for complex multi-split entries, account-type aware signs when duplicating transactions, and multi-currency exchange rates in Telegram bot.",
				Group:       "Bot",
				Size:        SizeL,
				Tier:        Tier2,
				Done:        false,
				Tag:         "Telegram",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "5",
				Title:       "REST API endpoints for /ledger/accounts",
				Description: "Add JSON controller endpoints for resources \"/accounts\", Account, only: [:index, :show, :create, :update, :delete] under the /ledger/ API scope.",
				Group:       "API",
				Size:        SizeM,
				Tier:        Tier2,
				Done:        false,
				Tag:         "REST",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "6",
				Title:       "Country selection ordering and i18n",
				Description: "Prioritize frequent countries (e.g. Spain/user home country) in contact/invoice forms and localize country names with :countries_i18n according to user locale.",
				Group:       "Web",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "i18n",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
			{
				ID:          "7",
				Title:       "Monaco background web worker configuration",
				Description: "Configure MonacoEnvironment.getWorkerUrl / getWorker in monaco_bundle.js to prevent fallback to main thread for bracket matching and diff computation.",
				Group:       "Web",
				Size:        SizeS,
				Tier:        Tier3,
				Done:        false,
				Tag:         "Assets",
				InsertedAt:   now,
				UpdatedAt:   now,
			},
		},
	}

	return []*Project{dymmer, conta}
}
